import EditIcon from './edit.svg'
import CheckSquare from './check-square.svg'
import UpIcon from './up.svg'
import DownIcon from './down.svg'
import BookmarkIcon from './bookmark.svg'
import FilterIcon from './filter.svg'
import VisibilityIcon from './visibility.svg'
import PencilEditIcon from './pencil-edit.svg'
import GreenLogoutIcon from './green-logout.svg'
import RedLogoutIcon from './red-logout.svg'
import ThreeDotsIcon from './three-dots.svg'
import GreenDownloadIcon from './green-download.svg'
import InfoIcon from './info.svg'
import GreenCheckIcon from './green-check.svg'
import RedCrossIcon from './red-cross.svg'
import MaximizeIcon from './maximize.svg'
import MinimizeIcon from './minimize.svg'
import UpdatePlanIcon from './update-plan.svg'
import SoftDeleteIcon from './soft-delete.svg'
import HardDeleteIcon from './hard-delete.svg'

export {EditIcon, UpdatePlanIcon, HardDeleteIcon, SoftDeleteIcon,  CheckSquare, UpIcon, DownIcon, BookmarkIcon, FilterIcon, VisibilityIcon, PencilEditIcon, GreenLogoutIcon, RedLogoutIcon, MaximizeIcon, MinimizeIcon, ThreeDotsIcon, GreenDownloadIcon, InfoIcon,GreenCheckIcon,RedCrossIcon}